### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by DmitryMyadzelets** [ActionSeeker/AutomatonExplorer#1]
When you put the example *A -> aA|BG* given for CNF Generator, it ends up with the error: "Error : Context Sensitive Rule at Line 1".

Btw, please, provide an example the Automaton Minimizer.

**Comment by ActionSeeker** [comment]
Hey Dmitry!
The issue has been resolved. While jQuery captures spacebar and locks it, apparently copying and pasting a production rule with spaces created the problem. This has been fixed.
Use production rules of the form A->Bc i.e. no space between the variables/terminals and the arrow.
